allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  es5-ext: false
  fsevents: false
  gatsby: true
  gatsby-cli: true
  gatsby-telemetry: true
  lmdb: true
  mozjpeg: true
  msgpackr-extract: true
  pngquant-bin: true
  sharp: true
